### ISSUE TITLE
Wheels for 3.12

### ISSUE THREAD

**Issue by tl24** [MKuranowski/aiocsv#22]
Could you build wheels for python 3.12?  I see that 3.12 support was added with #17 but currently I'm not seeing any wheels for it on pypi.

**Comment by MKuranowski** [comment]
That's probably because [cibuildwheel](https://github.com/pypa/cibuildwheel) didn't support building 3.12 wheel at the time of release. I'd need to push a new release to trigger a rebuild, which is a bit annoying. How much do you need the wheels anyway? It's a single C file, it shouldn't add that much overhead to install times.

**Comment by MKuranowski** [comment]
Published with v1.3.0
