### ISSUE TITLE
Handling CSV Files with Mixed Encodings Using aiocsv

### ISSUE THREAD

**Issue by mydu27** [MKuranowski/aiocsv#32]
I’m using FastAPI to upload CSV files and read the contents of two specific columns. Below is my FastAPI code for the upload process:

      import aiofiles
      from aiopath import AsyncPath
      import pandas as pd
      from aiocsv import AsyncDictReader
      from starlette.responses import JSONResponse
      from fastapi import UploadFile, File, APIRouter,  HTTPException
      router = APIRouter()

      @router.post("/csv-report")
      async def upload_dataset_csv_report(*,
                                          file: UploadFile = File(...)):
          target_folder = AsyncPath(settings.CSV_REPORT_PATH)
          if not await target_folder.exists():
              await target_folder.mkdir(exist_ok=True, parents=True)
          target_file_path = target_folder / (get_uuid() + '.csv')
          async with aiofiles.open(target_file_path, 'wb') as f:
              while True:
                  content = await file.read(4096)
                  if not content:
                      break
                  await f.write(content)
          await analysis_csv_report(csv_file_path=target_file_path)
          if await target_file_path.exists():
              await target_file_path.unlink()
          return JSONResponse(status_code=200, content='successful!')

To process the uploaded CSV, I use aiocsv. Here's the code:

      async def analysis_csv_report(csv_file_path: str, 
                                  columns=['StudyInstanceUID', 'DiagnosisReport']):
        async with aiofiles.open(csv_file_path, mode="r", errors="ignore") as file:
            first_line = await file.readline()
            headers = first_line.strip().split(",")
        missing_columns = [col for col in columns if col not in headers]
        if missing_columns:
            raise HTTPException(status_code=400, detail="CSV file is missing required headers")
        reader = AsyncDictReader(file, fieldnames=headers)
        async for row in reader:
            extracted_data = {col: row[col] for col in columns}
            logger.info(extracted_data)

The issue I’ve encountered is that users may upload CSV files where each line has a different encoding. This results in some lines being correctly read, while others have garbled Chinese characters.

For example, after using charset-normalizer to detect the encoding of each line, I found the following:

      Line 19483: Encoding=GB18030, Confidence=1.0
      Line 19484: Encoding=CP949, Confidence=1.0
      Line 19485: Encoding=CP949, Confidence=1.0
      Line 19486: Encoding=CP949, Confidence=1.0
      Line 19487: Encoding=CP949, Confidence=1.0
      Line 19488: Encoding=GB18030, Confidence=1.0
      Line 19489: Encoding=GB18030, Confidence=1.0
      Line 19490: Encoding=CP949, Confidence=1.0
      Line 19491: Encoding=CP949, Confidence=1.0
      Line 19492: Encoding=CP949, Confidence=1.0
      Line 19493: Encoding=GB18030, Confidence=1.0
      Line 19494: Encoding=CP949, Confidence=1.0
      Line 19495: Encoding=utf-8, Confidence=1.0

With so many different encodings, some lines read successfully, while others result in garbled text. I’ve tried converting everything to utf-8, latin-1, and other encodings, but none of these worked.

However, when using pandas.read_csv(), the file reads perfectly fine, with all lines displaying the correct Chinese characters. Here’s the Pandas implementation that works without issues:

    async def analysis_csv_report(csv_file_path: str, columns=['StudyInstanceUID', 'DiagnosisReport']):
      df = pd.read_csv(csv_file_path)
      missing_columns = [col for col in columns if col not in df.columns]
      if missing_columns:
          raise HTTPException(status_code=400, detail="failed") 
      for _, row in df.iterrows():
          extracted_data = {col: row[col] for col in columns}
          logger.info(extracted_data)

**Environment:**
Python version: 3.9.13
aiocsv version: 1.2.4
pandas version: 1.3.4
On both Windows and Linux, pandas.read_csv() reads the file perfectly, with no issues.
With **aiocsv**, the file reads correctly on my Windows machine, but on a Linux server running Docker (using the same Python and library versions), some lines result in garbled Chinese characters. The issue occurs specifically in the Linux environment.

**My question is:**
1. What is the difference between how aiocsv and pandas handle CSV files with mixed encodings?
2. Why does aiocsv work on my Windows machine but fail on the Linux Docker container, despite using the same versions of Python and libraries?
3. Is there a way to use aiocsv to resolve this issue with mixed encodings, similar to how pandas.read_csv() works seamlessly?
Thank you for your help!

**Comment by MKuranowski** [comment]
I think this is an issue with you not understanding how Python deals with encodings, text and binary based IO. See [Python's IO overwiew](https://docs.python.org/3/library/io.html#io-overview). Binary IO returns the bytes from a file as-is, as `bytes`. With Text IO, Python automatically decodes the raw bytes from a file into a sequence of Unicode codepoints, as `str`.

Both the builtin `csv` module and `aiocsv` work on the latter. This means that it is the caller's responsibility to ensure the file is decoded correctly. You don't provide any encoding to `aiofiles.open`, and it falls back to your user's locale encoding.

To answer your questions directly:

1. I do not know how pandas deals with encoding of CSV files. In aiocsv it is the caller's responsibility to decode the file correctly.
2. Because the user's locale encoding is different, on Unix systems it most likely is UTF-8, on Windows it most likely is an appropriate code page. See [locale.getpreferredencoding](https://docs.python.org/3/library/locale.html#locale.getpreferredencoding).
3. You need to open files with the correct encoding. See the `encoding` parameter of [open](https://docs.python.org/3/library/functions.html#open) (this also applies to aiofiles.open, as it's a simple wrapper around the builtin function).

Closing as this is the correct behavior, the same thing would happen with the builtin `csv` module when files are opened with an incorrect encoding.

**Comment by MKuranowski** [comment]
In general, if each line of your file is in different encodings, that means that the whole file was written incorrectly. From a `csv` point of view - what if the delimiter (or worse, the newline) is encoded differently on each line?

Just fix your file to UTF-8, you could do this on the file by implementing the `WithAsyncRead` interface over an async binary IO file; or by re-writing the file on disk.
